<section class="loaded-page-main-container">
	<div class="loaded-page-content">
		<aside class="congreso-content">
			<ul>
				<li>
					<p>
						<span class="text-left">Miembros al día ASOCIMANO</span>
						<span class="text-right">$ 550.000</span>
						<br />
						<span class="text-left">No miembros</span>
						<span class="text-right">$ 700.000</span>
					</p>
				</li>
				<li>
					<p>
						<span class="text-left">Miembros al día ASCOTEMA</span>
						<span class="text-right">$ 550.000</span>
					</p>
				</li>
				<li>
					<p>
						<span class="text-left">Residente, estudiante, y medico general Cirujano plástico, ortopedista</span>
						<span class="text-right" style="bottom:0;">$ 400.000</span>
					</p>
				</li>
				<li>
					<p>
						<span class="text-left">General y FT o TO internacional</span>
						<span class="text-right">$ 300 USD</span>
					</p>
				</li>
				<li>
					<p>
						<span class="text-left" style="max-width:300px;line-height:1.5em;">Inscripción de trabajos libres, de ingreso y de poster, hasta:30 de Mayo de 2014<br />Entrega de trabajos libres, de ingreso y poster, hasta: 30 de Junio de 2014</span>
					</p>
				</li>
				<li>
					<p style="padding:6px 0;"></p>
				</li>
				<li>
					<p>
						<span class="text-title">INVITADOS</span><br />
						<span class="text-invite invite-1">Dr. Michel Merle. <span class="invite-country">Francia</span></span>
						<span class="text-invite invite-2">Dr. Christophe Mathulin. <span class="invite-country">Francia</span></span>
						<span class="text-invite invite-3">Dr. Juan Gonzalez del Pino. <span class="invite-country">España</span>
					</p>
				</li>
			</ul>
		</aside>
	</div>
</section>