<!doctype html>
<html lang="<?php echo LANG ?>">
    <head>
        <meta charset="<?php echo CHARSET ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?php echo getTitleDocument(); ?></title>
        <?php wp_head(); ?>
    </head>

    <body>
	    <section id="wrapper-main-content">
		    <section id="wrapper-content">
		        <div class="line-shadow sh-left"></div>
		        <div class="line-shadow sh-top"></div>
		        <div class="line-shadow sh-right"></div>
		        <div class="container">
                <?php getPageLayout( 'header' ); ?>
